version: '3.4'

services:
  simplcommerce:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    volumes:
      - ${VOLUMES_BASEPATH}/logs:/app/logs
      - ${VOLUMES_BASEPATH}/usercontents:/app/wwwroots/user-content
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - ${VOLUMES_BASEPATH}/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
